int main(){
	__asm__ __volatile__ (
			"mov $1, %ebx;"
			"top: imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"imul $-1, %ebx, %eax;"
			"jmp top;"
	);
	return(0);
}
